name: "Publish"

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal
    - name: Pack
      run: dotnet pack --no-build -c Release -o .
    - name: Push To nuget.org
      run: dotnet nuget push *.nupkg -k ${{ secrets.TOKEN }} -s https://nuget.pkg.github.com/nebioo/index.json
